name: containers
on:
  push:
    branches: main
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      strava: ${{ steps.filter.outputs.strava }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            strava:
              - 'strava/**'
  strava:
    needs: changes
    if: ${{ needs.changes.outputs.strava == 'true' }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Tag
        shell: bash
        run: echo "tag=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-${GITHUB_SHA:0:7}-$(date +%s)" >> $GITHUB_OUTPUT
        id: generate_tag
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: strava/
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/bobdoah/strava-uploader:${{ steps.generate_tag.outputs.tag }}
